import Foundation

func printVersion() {
    print("Kodema v\(KODEMA_VERSION)")
}

func printHelp() {
    print("\n\(boldColor)Kodema v\(KODEMA_VERSION) - iCloud to Backblaze B2 Backup Tool\(resetColor)")
    print("\(boldColor)═══════════════════════════════════════════════════════════════\(resetColor)")
    print("\nUsage:")
    print("  kodema <command> [options]")
    print("\nCommands:")
    print("  \(boldColor)backup\(resetColor)       Incremental backup with snapshots and versioning")
    print("  \(boldColor)mirror\(resetColor)       Simple mirroring (uploads all files)")
    print("  \(boldColor)cleanup\(resetColor)      Clean up old backup versions per retention policy")
    print("  \(boldColor)restore\(resetColor)      Restore files from backup snapshots")
    print("  \(boldColor)test-config\(resetColor)  Validate configuration without uploading")
    print("  \(boldColor)list\(resetColor)         List all folders in iCloud Drive")
    print("  \(boldColor)version\(resetColor)      Show version information")
    print("  \(boldColor)help\(resetColor)         Show this help message")
    print("\nOptions:")
    print("  \(boldColor)--config\(resetColor), \(boldColor)-c\(resetColor) <path>         Specify custom config file path")
    print("  \(boldColor)--dry-run\(resetColor), \(boldColor)-n\(resetColor)               Preview changes without making them")
    print("  \(boldColor)--snapshot\(resetColor) <timestamp>   Restore specific snapshot (for restore)")
    print("  \(boldColor)--path\(resetColor) <path>           Restore specific file/folder (for restore)")
    print("  \(boldColor)--output\(resetColor) <path>         Custom restore location (for restore)")
    print("  \(boldColor)--force\(resetColor)                  Skip overwrite confirmation (for restore)")
    print("  \(boldColor)--list-snapshots\(resetColor)        List available snapshots (for restore)")
    print("\nExamples:")
    print("  kodema test-config                         Validate config and test B2 connection")
    print("  kodema backup                              Incremental backup with default config")
    print("  kodema backup --dry-run                    Preview what would be backed up")
    print("  kodema mirror --config ~/my-config.yml     Simple mirror with custom config")
    print("  kodema cleanup -c ~/my-config.yml          Clean up with custom config")
    print("  kodema cleanup --dry-run                   Preview what would be deleted")
    print("  kodema restore                             Interactive snapshot selection and restore")
    print("  kodema restore --snapshot 2024-11-27_143022    Restore specific snapshot")
    print("  kodema restore --path Documents/file.txt   Restore specific file from latest")
    print("  kodema restore --dry-run --snapshot 2024-11-27_143022    Preview restore")
    print("  kodema restore --list-snapshots            List available snapshots")
    print("  kodema list                                Discover iCloud folders")
    print("\n\(boldColor)Backup vs Mirror:\(resetColor)")
    print("  • \(boldColor)backup\(resetColor) - Creates versioned snapshots, only uploads changed files")
    print("  • \(boldColor)mirror\(resetColor) - Uploads all files every time, no versioning")
    print("\n\(boldColor)═══════════════════════════════════════════════════════════════\(resetColor)\n")
}
